### ISSUE TITLE
pomoč pri zemljevidu

### ISSUE THREAD

**Issue by lencdo** [lencdo/APPR-2017-18#2]
V poročilo sem dodal zemljevid porabe interneta po Evropi. Zanima me, kako bi lahko nastavil barve tako, da bi bile vse države pobarvane na primer modro, le da bi bile tiste države z večjo uporabo temnejše. Trenutno so namreč vse države pobarvane različno in se iz zemljevida ne da nič razbrati.

Prav tako sem želel, da bi imela vsaka država nekje v sredini narisan krog, katerega velikost bi povedala, kako hitro se razvija uporaba interneta v zadnjih letih. Kot razumem je trenutno problem v tem, da program naredi en krog na vsaki koordinati na meji s sosednjo državo, rad pa bi, da ima vsaka država po en krog (npr. v glavnem mestu, lahko pa tudi kje drugje).

**Comment by jaanos** [comment]
Da nastaviš barve državam, naj bo parameter `fill` znotraj `aes`. Pri tem ni potrebno podati imena razpredelnice, če si jo pred tem dal kot parameter `data` k `ggplot` ali ustreznemu `geom_*`. Za trenutno različno obarvanost je sicer kriv `scale_fill_identity` - tega nadomesti s `scale_fill_continuous`, če želiš nastaviti barvo za države brez podatkov.

Točko za vsako državo najlažje narišeš v povprečje točk na njenem robu:
```R
zema <- ggplot() + geom_polygon(data = tess %>% filter(long > -30),
                                aes(x = long, y = lat, group = group, fill = `Uporaba interneta`)) +
  geom_point(data = tess  %>% filter(long > -20, lat > 30, lat < 78) %>% drop_na(Koeficient) %>%
               group_by(id) %>% summarise(x = mean(long), y = mean(lat),
                                          Koeficient = max(Koeficient)),
             aes(x = x, y = y, size = Koeficient), color="gray") +
  coord_map(xlim = c(-25, 40), ylim = c(32, 72)) + scale_size(name = "T", range = c(0.2, 2)) +
  scale_fill_continuous(na.value = "white")
```
Ker imaš koeficient za vsako državo že v `tess`, ga je bilo treba pridobiti kot maksimum v vseh ustreznih vrsticah (lahko bi vzel tudi minimum ali povprečje). Pred tem je bila uporabljena funkcija `drop_na` iz knjižnice `tidyr`, da se točke ne izrišejo za države, ki tega podatka nimajo.

Pri izrisovanju se na dveh mestih točke na zemljevidu filtrirajo: prvi filter preprečuje izrisovanje točk za Rusijo, ki so vzhodno od 180. poldnevnika (te bi se kazale v vodoravnih belih črtah čez zemljevid), drugi pa preprečuje, da bi ozemlja izven zemljevida potegnila točke za Portugalsko, Francijo in Norveško izven njihovih osnovnih ozemelj.
